# Base validation rules
# These rules apply to all exchanges



- type: ExpectColumnValuesToBeUnique
  column: ISIN, RIC, BBGTicker

- type: ExpectColumnValuesToNotBeNull
  column: ISIN, RIC, BBGTicker

- type: ExpectColumnValuesToNotBeNull
  column: Exchange, Currency, countryOfListing, IssuerName, SecurityType, IssueType, MinTradableQuantity


#- type: ExpectColumnValuesToBeInSet
#  column: Status
#  value_set:
#    - ACTIVE
#    - INACTIVE
#    - SUSPENDED

- type: ExpectColumnValuesToNotBeNull
  column: SecurityType

- type: ExpectColumnValuesToBeInSet
  column: SecurityType
  value_set:
    - Equity
    - Bond

- type: ExpectColumnValuesToBeInSet
  column: IssueType
  value_set:
    - EQ
    - BD

- type: ExpectColumnValuesToBeBetween
  column: MinTradableQuantity
  min_value: 1


# Conditional rules: only validated for rows where the condition is true.
# Syntax uses pandas query expressions in the `condition` field.

# When SecurityType is 'Bond', IssueType must be 'BD'
- type: ExpectColumnValuesToBeInSet
  column: IssueType
  value_set:
    - BD
  condition: "SecurityType == 'Bond'"

# When SecurityType is 'Equity', IssueType must be 'EQ'
- type: ExpectColumnValuesToBeInSet
  column: IssueType
  value_set:
    - EQ
  condition: "SecurityType == 'Equity'"

